//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookBuffet.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.Comment = new HashSet<Comment>();
        }
    
        public int EventId { get; set; }
        public string EventTitle { get; set; }
        public string EventLocation { get; set; }
        public string EventTime { get; set; }
        public System.DateTime EventDate { get; set; }
        public int EventDuration { get; set; }
        public string EventType { get; set; }
        public string EventDescription { get; set; }
        public string EventDetails { get; set; }
        public string EventInvite { get; set; }
        public int UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual User User { get; set; }
    }
}
